#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TBrowser.h"
#include "TH2.h"
#include "TRandom.h"
void tree1w(){
  //create the file, the Tree and a few branches
  TFile f("tree1.root","recreate");
  TTree t1("t1","a simple Tree with simple variables");
  Float_t x, y, z;
  Double_t random;
  Int_t ev;
  t1.Branch("x",&x,"x/F");
  t1.Branch("y",&y,"y/F");
  t1.Branch("z",&z,"z/F");
  //fill the tree
  for (Int_t i=0;i<1000;i++) {
    gRandom->Rannor(x,y);
    z=x+y;
    t1.Fill();
  }

  //Writing the tree to root file
  t1.Write();
}
void tree1r()
{
  //read the Tree generated by tree1w and fill two histograms

  //note that we use "new" to create the TFile and TTree objects !
  //because we want to keep these objects alive when we leave this function.
  TFile *f = new TFile("tree1.root");
  TTree *t1 = (TTree*)f->Get("t1");
  Float_t x, y, z;
  Double_t random;
  Int_t ev;
  t1->SetBranchAddress("x",&x);
  t1->SetBranchAddress("y",&y);
  t1->SetBranchAddress("z",&z);
  //create two histograms
   
  TH1F *hx   = new TH1F("hx","x distribution",100,0,70);
  TH2F *hxy = new TH2F("hxy","y vs x ; x;y",30,-3,3,30,-3,3);
  Long64_t nentries = t1->GetEntries();
  for (int i=0;i<nentries;i++) {
    t1->GetEntry(i);
    hx->Fill(x);
    hxy->Fill(x,y);
    hxy->GetXaxis()->CenterTitle();
    hxy->GetYaxis()->CenterTitle();
    hxy->Draw("COLZ");
    hx->SetFillColor(kBlue);
  }

  //we do not close the file. We want to keep the generated histograms
  //we open a browser and the TreeViewer
  if (gROOT->IsBatch()) return;
  new TBrowser();
  t1->StartViewer();
  // in the browser, click on "ROOT Files", then on "tree1.root".
  //     you can click on the histogram icons in the right panel to draw them.
  // in the TreeViewer, follow the instructions in the Help button.
}

void tree1() {
  tree1w();
  tree1r();
}



